version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  # build-and-push-docker-image
  build-and-push-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ianacodev/deployment-demo
      - docker/push:
          image: ianacodev/deployment-demo

workflows:
  deploy_pipeline:
    jobs:
      - build-and-push-docker-image
