version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:18.12.1-browsers
  working_directory: ~/deployment-demo

orbs:
  browser-tools: circleci/browser-tools@1.4.1
  docker: circleci/docker@2.2.0

jobs:
  # unit-tests
  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/deployment-demo
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome Install
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Unit Tests
          command: npm run test:ci

  # build-and-push-docker-image
  build-and-push-docker-image:
    <<: *defaults
    executor: docker/docker
    steps:
      - attach_workspace:
          at: ~/deployment-demo
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ianacodev/deployment-demo
      - docker/push:
          image: ianacodev/deployment-demo

workflows:
  build_deploy_pipeline:
    jobs:
      - unit_tests:
      - build-and-push-docker-image:
          requires:
            - unit_tests
