apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: deployment-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      labels:
        app: deployment-demo
    spec:
      containers:
        - name: deployment-demo
          image: ianacodev/deployment-demo:b76ea5ec275cdf0c49c0bc0d18d0254c560179ad
          ports:
            - containerPort: 80
